version: '3'
services:
  api:
    build: ./fastener-api-main
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres://postgres:postgres@db:5432/fastener
    depends_on:
      - db

  frontend:
    build: ./fastener-frontend-v2-main
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8080

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastener
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
